spring:
  application:
    name: digitalwallet

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/digital-wallet
    username: postgres
    password: 123

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    #defer-datasource-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show:
        details: always

external-services:
  transaction-authorizer:
    base-uri: https://util.devi.tools/api/
  notify:
    base-uri: https://util.devi.tools/api/