server:
  port: 8081
spring:
  application:
    name: digitalwalletevents
  threads:
    virtual:
      enabled: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/digital-wallet
    username: postgres
    password: 123

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        format_sql: false


transaction-event:
  exchange: transaction-event-exchange
  routing-key: transaction-event-routing-key