server:
  port: 8081
spring:
  application:
    name: digitalwalletevents
  threads:
    virtual:
      enabled: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/digital-wallet
    username: postgres
    password: 123

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        format_sql: false

transaction-event:
  exchange: transaction-event-exchange
  routing-key: transaction-event-routing-key

resilience4j.circuitbreaker:
  instances:
    transaction-notify-gateway:
      slidingWindowType: COUNT_BASED #TIME_BASED // COUNT_BASED
      slidingWindowSize: 4
      minimumNumberOfCalls: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 2
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException.BadGateway
        - org.springframework.web.client.HttpServerErrorException.GatewayTimeout
        - org.springframework.web.client.HttpServerErrorException.InternalServerError
        - org.springframework.web.client.HttpServerErrorException.ServiceUnavailable

resilience4j.retry:
  instances:
    transaction-notify-gateway:
      maxAttempts: 5
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException.BadGateway
        - org.springframework.web.client.HttpServerErrorException.GatewayTimeout
        - org.springframework.web.client.HttpServerErrorException.InternalServerError
        - org.springframework.web.client.HttpServerErrorException.ServiceUnavailable


external-services:
  transaction-notify:
    base-uri: "https://util.devi.tools/api"
    from-email: "digital-wallet@email.com"